version: 2
updates:
  - package-ecosystem: "pipenv"
    directory: "/app"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
